# Stage 1: Build React
FROM node:20-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Share build files via volume
FROM alpine
WORKDIR /app
COPY --from=build /app/build ./build
CMD ["tail", "-f", "/dev/null"]