# Generated by Django 6.0.7 on 2026-08-26 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A Legacy of Healthcare Leadership & Patient Care', max_length=255)),
                ('subtitle', models.TextField(default='Medison Hospital stands as a beacon of modern medical care...')),
                ('who_we_are_image', models.ImageField(upload_to='about/')),
                ('vision_text', models.TextField()),
                ('mission_text', models.TextField()),
                ('chairman_name', models.CharField(default='Dr. Ahmed Rahman', max_length=150)),
                ('chairman_role', models.CharField(default='Chairman, Medison Hospital', max_length=150)),
                ('chairman_image', models.ImageField(upload_to='about/chairman/')),
                ('chairman_message', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us Overview',
                'verbose_name_plural': 'About Us Overview',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(help_text='e.g., cardiology, neurology', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('surgical', 'Surgical & Trauma'), ('general', 'General Medicine'), ('critical', 'Critical Care & Emergency'), ('diagnostic', 'Diagnostic & Imaging'), ('specialized', 'Specialized Care'), ('maternal', 'Maternal & Child Health'), ('dental_eye', 'Dental & Ophthalmology'), ('wellness', 'Wellness & Rehabilitation')], default='general', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('icon_name', models.CharField(default='FaStethoscope', help_text='React Icon Name (e.g., FaHeartbeat, FaBrain, FaBone, FaBaby, FaFemale, FaStethoscope, FaProcedures, FaTooth, FaEye)', max_length=50)),
                ('doctors_count', models.CharField(default='10 Specialist Doctors', max_length=100)),
                ('availability', models.CharField(default='24/7 Emergency Care', max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#0046AD', help_text='Hex code (e.g., #E31B23 or #0046AD)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('degrees', models.CharField(max_length=255)),
                ('hospital', models.CharField(max_length=255)),
                ('experience', models.CharField(help_text='e.g. 12+ Years Exp.', max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('reviews', models.CharField(default='0+', max_length=50)),
                ('consultation_fee', models.CharField(help_text='e.g. $50 / ৳1,500', max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('theme_color', models.CharField(default='#0046AD', max_length=20)),
                ('availability', models.JSONField(default=list, help_text='["Mon - Wed (10 AM - 2 PM)", "Sat (4 PM - 8 PM)"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Emergency', 'Emergency'), ('Inpatient', 'Inpatient'), ('Specialized', 'Specialized'), ('Digital', 'Digital'), ('Home Care', 'Home Care'), ('Facility', 'Facility')], max_length=50)),
                ('image', models.URLField(max_length=500)),
                ('theme_color', models.CharField(default='#0046AD', max_length=20)),
                ('rating', models.CharField(default='5.0', max_length=10)),
                ('reviews', models.CharField(default='0+', max_length=20)),
                ('short_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='DepartmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Coronary Angiography & Angioplasty', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='hospital.department')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., 24/7 Emergency Service', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='hospital.aboutusoverview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tests/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_time', models.CharField(max_length=100)),
                ('preparation', models.TextField()),
                ('description', models.TextField()),
                ('parameters', models.JSONField(default=list, help_text="List of parameters e.g. ['Hemoglobin', 'WBC Count']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='hospital.category')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='hospital.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hospital.service')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.specialty'),
        ),
    ]
