# Generated by Django 4.2.30 on 2026-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='theme_color',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='title',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degrees',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=255),
        ),
    ]
