# Generated by Django 4.2.30 on 2026-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_doctor_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='departments',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
