# Generated by Django 4.2.30 on 2026-09-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_bannerslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hospital_video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
    ]
