# Generated by Django 4.2.30 on 2026-09-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='who_we_are_image',
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='hero_bg_image',
            field=models.ImageField(blank=True, help_text='About Us পেজের Hero Banner-এর ব্যাকগ্রাউন্ড ছবি', null=True, upload_to='about/hero/'),
        ),
    ]
