# Generated by Django 4.2.30 on 2026-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_aboutusoverview_who_we_are_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Overview',
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='hospital_video',
            field=models.FileField(blank=True, help_text='হাসপাতালের ভিডিও ট্যুর (MP4/WebM)', null=True, upload_to='about/videos/'),
        ),
    ]
