# Generated by Django 4.2.30 on 2026-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_delete_overview_aboutusoverview_hospital_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='chamber_day_time',
            field=models.TextField(blank=True, help_text='e.g., Sat - Wed (5:00 PM - 8:00 PM)', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, help_text='Doctor Correction / Confirmation status', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.CharField(blank=True, help_text='e.g., Senior Consultant, Associate Professor', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degrees',
            field=models.TextField(help_text='Doctor Qualifications'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(help_text='Affiliation', max_length=255),
        ),
    ]
