# Generated by Django 4.2.30 on 2026-09-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_doctor_chamber_day_time_doctor_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='departments',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospital.specialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='departments',
            field=models.ManyToManyField(help_text='ডাক্তারটি যে ডিপার্টমেন্টগুলোর অধীনে থাকবেন সেগুলো সিলেক্ট করুন', related_name='doctors', to='hospital.department'),
        ),
    ]
