# Generated by Django 4.2.30 on 2026-09-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_remove_doctor_departments_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('pediatric_surgery', 'Pediatric & General Surgery'), ('general_laparoscopic', 'General, Laparoscopic & Colorectal Surgery'), ('gynecology_obs', 'Gynecology & Obstetrics'), ('anesthesia_pain', 'Anesthesia & Pain Management'), ('ultrasonography', 'Ultrasonography & Sonology'), ('ophthalmology', 'Ophthalmology (Eye)'), ('general_medicine', 'Medicine, Nephrology, Diabetes, Cardiology & Respiratory'), ('orthopedics', 'Orthopedics, Spine & Rheumatology'), ('dental', 'Dental Care'), ('neurosurgery', 'Neurosurgery'), ('oncology', 'Oncology (Cancer Care)'), ('physical_medicine', 'Physical Medicine & Rehabilitation'), ('ent', 'ENT (Ear, Nose & Throat)'), ('public_health', 'Public Health & Experienced Medicine'), ('ultrasound_gynae', 'Ultrasound & Gynecology')], default='general', max_length=20),
        ),
    ]
