# Generated by Django 4.2.30 on 2026-09-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_department_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='chairman_message',
        ),
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='chairman_name',
        ),
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='chairman_role',
        ),
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='mission_text',
        ),
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='title',
        ),
        migrations.RemoveField(
            model_name='aboutusoverview',
            name='vision_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='doctors_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='departmentfeature',
            name='title',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='chamber_day_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='degrees',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='position',
        ),
        migrations.RemoveField(
            model_name='featureitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='hospitalstat',
            name='title',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='preparation',
        ),
        migrations.RemoveField(
            model_name='medicaltest',
            name='report_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.RemoveField(
            model_name='servicefeature',
            name='title',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='name',
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='chairman_message_bn',
            field=models.TextField(blank=True, default='', verbose_name='Chairman Message (BN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='chairman_message_en',
            field=models.TextField(blank=True, default='', verbose_name='Chairman Message (EN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='chairman_name_bn',
            field=models.CharField(default='ডাঃ আহমেদ রহমান', max_length=150, verbose_name='Chairman Name (BN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='chairman_name_en',
            field=models.CharField(default='Dr. Ahmed Rahman', max_length=150, verbose_name='Chairman Name (EN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='chairman_role_bn',
            field=models.CharField(default='চেয়ারম্যান, মেডিসন হাসপাতাল', max_length=150, verbose_name='Chairman Role (BN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='chairman_role_en',
            field=models.CharField(default='Chairman, Medison Hospital', max_length=150, verbose_name='Chairman Role (EN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='mission_text_bn',
            field=models.TextField(blank=True, default='', verbose_name='Mission Text (BN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='mission_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Mission Text (EN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='subtitle_bn',
            field=models.TextField(default='মেডিসন হাসপাতাল আধুনিক চিকিৎসা সেবার এক অনন্য প্রতীক...', verbose_name='Subtitle (BN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='subtitle_en',
            field=models.TextField(default='Medison Hospital stands as a beacon of modern medical care...', verbose_name='Subtitle (EN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='title_bn',
            field=models.CharField(default='স্বাস্থ্যসেবায় নেতৃত্ব এবং রোগীর যত্নের একটি বিশ্বস্ত ঐতিহ্য', max_length=255, verbose_name='Title (BN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='title_en',
            field=models.CharField(default='A Legacy of Healthcare Leadership & Patient Care', max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='vision_text_bn',
            field=models.TextField(blank=True, default='', verbose_name='Vision Text (BN)'),
        ),
        migrations.AddField(
            model_name='aboutusoverview',
            name='vision_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Vision Text (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bn',
            field=models.CharField(default='', max_length=100, verbose_name='Category Name (BN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Category Name (EN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='availability_bn',
            field=models.CharField(default='২৪/৭ জরুরি সেবা', max_length=100, verbose_name='Availability (BN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='availability_en',
            field=models.CharField(default='24/7 Emergency Care', max_length=100, verbose_name='Availability (EN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_bn',
            field=models.TextField(blank=True, default='', verbose_name='Description (BN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='doctors_count_bn',
            field=models.CharField(default='১০ জন বিশেষজ্ঞ ডাক্তার', max_length=100, verbose_name='Doctors Count (BN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='doctors_count_en',
            field=models.CharField(default='10 Specialist Doctors', max_length=100, verbose_name='Doctors Count (EN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_bn',
            field=models.CharField(default='', max_length=255, verbose_name='Department Name (BN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Department Name (EN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='tagline_bn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tagline (BN)'),
        ),
        migrations.AddField(
            model_name='department',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tagline (EN)'),
        ),
        migrations.AddField(
            model_name='departmentfeature',
            name='title_bn',
            field=models.CharField(default='', max_length=255, verbose_name='Title (BN)'),
        ),
        migrations.AddField(
            model_name='departmentfeature',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='chamber_day_time_bn',
            field=models.TextField(blank=True, null=True, verbose_name='Chamber Time (BN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='chamber_day_time_en',
            field=models.TextField(blank=True, null=True, verbose_name='Chamber Time (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degrees_bn',
            field=models.TextField(blank=True, default='', verbose_name='Degrees (BN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='degrees_en',
            field=models.TextField(blank=True, default='', verbose_name='Degrees (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_bn',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hospital (BN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Hospital (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_bn',
            field=models.CharField(default='', max_length=150, verbose_name='Doctor Name (BN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_en',
            field=models.CharField(default='', max_length=150, verbose_name='Doctor Name (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position_bn',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Position (BN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Position (EN)'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='title_bn',
            field=models.CharField(default='', max_length=150, verbose_name='Title (BN)'),
        ),
        migrations.AddField(
            model_name='featureitem',
            name='title_en',
            field=models.CharField(default='', max_length=150, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='hospitalstat',
            name='title_bn',
            field=models.CharField(default='', max_length=100, verbose_name='Stat Title (BN)'),
        ),
        migrations.AddField(
            model_name='hospitalstat',
            name='title_en',
            field=models.CharField(default='', max_length=100, verbose_name='Stat Title (EN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='description_bn',
            field=models.TextField(blank=True, default='', verbose_name='Description (BN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='name_bn',
            field=models.CharField(default='', max_length=255, verbose_name='Test Name (BN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Test Name (EN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='preparation_bn',
            field=models.TextField(blank=True, default='', verbose_name='Preparation (BN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='preparation_en',
            field=models.TextField(blank=True, default='', verbose_name='Preparation (EN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='report_time_bn',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Report Time (BN)'),
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='report_time_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Report Time (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc_bn',
            field=models.TextField(blank=True, default='', verbose_name='Short Description (BN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc_en',
            field=models.TextField(blank=True, default='', verbose_name='Short Description (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_bn',
            field=models.CharField(default='', max_length=255, verbose_name='Title (BN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='title_bn',
            field=models.CharField(default='', max_length=255, verbose_name='Feature (BN)'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Feature (EN)'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_bn',
            field=models.CharField(default='', max_length=100, verbose_name='Specialty (BN)'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='Specialty (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutusoverview',
            name='chairman_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/chairman/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('pediatric_surgery', 'Pediatric & General Surgery'), ('general_laparoscopic', 'General, Laparoscopic & Colorectal Surgery'), ('gynecology_obs', 'Gynecology & Obstetrics'), ('anesthesia_pain', 'Anesthesia & Pain Management'), ('ultrasonography', 'Ultrasonography & Sonology'), ('ophthalmology', 'Ophthalmology (Eye)'), ('general_medicine', 'Medicine, Nephrology, Diabetes, Cardiology & Respiratory'), ('orthopedics', 'Orthopedics, Spine & Rheumatology'), ('dental', 'Dental Care'), ('neurosurgery', 'Neurosurgery'), ('oncology', 'Oncology (Cancer Care)'), ('physical_medicine', 'Physical Medicine & Rehabilitation'), ('ent', 'ENT (Ear, Nose & Throat)'), ('public_health', 'Public Health & Experienced Medicine'), ('ultrasound_gynae', 'Ultrasound & Gynecology')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='#0046AD', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon_name',
            field=models.CharField(default='FaStethoscope', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='departments',
            field=models.ManyToManyField(related_name='doctors', to='hospital.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='parameters',
            field=models.JSONField(default=list),
        ),
    ]
