# Generated by Django 4.2.30 on 2026-09-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_aboutusoverview_chairman_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='service',
            name='reviews',
        ),
    ]
