# Generated by Django 4.2.30 on 2026-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='availability_bn',
        ),
        migrations.RemoveField(
            model_name='department',
            name='availability_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='doctors_count_bn',
        ),
        migrations.RemoveField(
            model_name='department',
            name='doctors_count_en',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tagline_bn',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tagline_en',
        ),
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('medicine', 'Medicine Department / মেডিসিন বিভাগ'), ('chest', 'Chest & Respiratory Department / বক্ষব্যাধি বিভাগ'), ('gynecology', 'Gynecology Department / গাইনী বিভাগ'), ('pediatrics', 'Pediatrics Department / শিশু বিভাগ'), ('orthopedics', 'Orthopedics Department / অর্থোপেডিক বিভাগ'), ('cardiology', 'Cardiology Department / কার্ডিওলজি বিভাগ'), ('ent', 'ENT Department / নাক-কান-গলা বিভাগ'), ('diabetes', 'Diabetes Department / ডায়াবেটিস বিভাগ'), ('physical_medicine', 'Physical Medicine & Rehabilitation / ফিজিক্যাল মেডিসিন এন্ড রিহ্যাবিলিটেশন'), ('neuromedicine', 'Neuromedicine Department / নিউরো মেডিসিন বিভাগ'), ('urology', 'Urology Department / ইউরোলজি বিভাগ'), ('ophthalmology', 'Ophthalmology (Eye) Department / চক্ষু বিভাগ'), ('nephrology', 'Nephrology Department / নেফ্রোলজী বিভাগ'), ('dermatology', 'Dermatology & Venereology / চর্ম ও যৌন বিভাগ'), ('general_surgery', 'General Surgery Department / জেনারেল সার্জারী বিভাগ'), ('dental', 'Dental Department / ডেন্টাল বিভাগ'), ('hematology', 'Hematology Department / রক্তরোগ বিভাগ')], default='medicine', max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.CharField(help_text='e.g., medicine, cardiology', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_bn',
            field=models.CharField(max_length=255, verbose_name='Department Name (BN)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Department Name (EN)'),
        ),
    ]
