# Generated by Django 4.2.30 on 2026-09-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_remove_department_availability_bn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaltest',
            name='price',
        ),
    ]
