# Generated by Django 4.2.30 on 2026-10-06 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_remove_medicaltest_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(db_index=True, max_length=50, verbose_name='Patient ID / রোগীর আইডি')),
                ('mobile_number', models.CharField(db_index=True, max_length=15, verbose_name='Mobile Number / মোবাইল নম্বর')),
                ('patient_name_en', models.CharField(max_length=150, verbose_name='Patient Name (English)')),
                ('patient_name_bn', models.CharField(max_length=150, verbose_name='রোগীর নাম (বাংলা)')),
                ('test_name_en', models.CharField(max_length=255, verbose_name='Test Name (English)')),
                ('test_name_bn', models.CharField(max_length=255, verbose_name='পরীক্ষার নাম (বাংলা)')),
                ('doctor_name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doctor Name (English)')),
                ('doctor_name_bn', models.CharField(blank=True, max_length=200, null=True, verbose_name='ডাক্তারের নাম (বাংলা)')),
                ('status', models.CharField(choices=[('Pending', 'Pending / প্রক্রিয়াধীন'), ('Ready', 'Ready / প্রস্তুত'), ('Delivered', 'Delivered / প্রদান করা হয়েছে')], default='Ready', max_length=20, verbose_name='Status / অবস্থা')),
                ('pdf_file', models.FileField(upload_to='reports/pdf/', verbose_name='PDF File / রিপোর্ট ফাইল')),
                ('report_date', models.DateField(verbose_name='Report Date / পরীক্ষার তারিখ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Report / মেডিকেল রিপোর্ট',
                'verbose_name_plural': 'Medical Reports / মেডিকেল রিপোর্টসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
